# Generated by Django 4.0.3 on 2022-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friend1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friend2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friend3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('away', 'Away'), ('online', 'Online'), ('busy', 'Busy'), ('offline', 'Offline')], default='Offline', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to=''),
        ),
    ]
